create table forma_pagamento (id bigint not null auto_increment, descricao varchar(100) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(60) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null, primary key (grupo_id, permissao_id)) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(100) not null, nome varchar(60) not null, primary key (id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, ativo bit not null, descricao varchar(100) not null, nome varchar(60) not null, preco decimal(19,2) not null, restaurante_id bigint not null, primary key (id)) engine=InnoDB;
create table restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(60), endereco_cep varchar(15), endereco_complemento varchar(80), endereco_logradouro varchar(80), endereco_numero varchar(10), nome varchar(60) not null, taxa_frete decimal(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null, primary key (restaurante_id, forma_pagamento_id)) engine=InnoDB;
create table usuario (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, email varchar(60) not null, nome varchar(60) not null, senha varchar(60) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null, primary key (usuario_id, grupo_id)) engine=InnoDB;
alter table cidade add constraint fk_estado_id foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint fk_permissao_grupo_id foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint fk_grupo_permissao_id foreign key (grupo_id) references grupo (id);
alter table produto add constraint fk_restaurante_id foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint fk_cozinha_id foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint fk_cidade_id foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint fk_forma_pagamento_resturante_id foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint fk_resturante_forma_pagamento_id foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint fk_grupo_usuario_id foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint fk_usuario_grupo_id foreign key (usuario_id) references usuario (id);